#!/bin/bash

# if I remember correctly,  -p (paired) requires to set stranding since version 2.0.0

#    --primary \ # no multimappers
#    --ignoreDup \

# -C = exclusion of chimeric reads (opposite strands and interchromosomal pairs)

bin/subread-2.0.0-source/bin/featureCounts \
    -a ref/star-hg19/gencode.v31lift37.annotation.gtf \
    -o "output/tables/gsam_featureCounts_readcounts.txt" \
    --tmpDir "/dev/shm/" \
    -p \
    -s 2 \
    -T 64 \
    --primary \
    -C \
    --ignoreDup \
    processed/AAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAP2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAS1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAS2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAT1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAT2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAU1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAU2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAV1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAV2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAW1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAW2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAX1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAX2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAY1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AAY2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ABA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ABA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ACA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ACA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ADA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ADA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AFA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AFA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AHA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AHA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AIA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AIA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AKA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AKA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ALA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ALA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AMA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AMA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AOA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AOA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AQA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AQA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/AZH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAO1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAO2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAR1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAR2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAS1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAS2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAT1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAT2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAU1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAU2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAW1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAW2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAX1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAX2/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAY1/Aligned.sortedByCoord.out.markdup.bam \
    processed/BAY2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAO1-replicate/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAO1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAO2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAV1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CAV2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBP2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBQ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBQ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBR1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBR2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBS1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBS2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBT1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBT2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBV1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CBV2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCW1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCW2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCZ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CCZ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/CDH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/DAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAO1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAO2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAP2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAQ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAQ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAT1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAT2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAU1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAU2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAV1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAV2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAW1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAW2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAY1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAY2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAZ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EAZ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBO1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBO2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBR1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBR2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBU1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBU2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBV1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBV2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBW1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBW2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBX1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBX2/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBY1/Aligned.sortedByCoord.out.markdup.bam \
    processed/EBY2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/ECN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAB2-replicate/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAP2/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAQ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/FAQ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAO1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAO2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAP1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAP2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAQ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAQ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAR1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAR2/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAS1/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAS2-replicate/Aligned.sortedByCoord.out.markdup.bam \
    processed/GAS2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/HAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAE1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAE2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAF1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAF2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAG1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAG2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAH1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAH2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAI1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAI2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAJ1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAJ2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAK1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAK2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAL1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAL2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAM1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAM2/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAN1/Aligned.sortedByCoord.out.markdup.bam \
    processed/JAN2/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAA1/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAA2/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAB1/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAB2/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAC1/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAC2/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAD1/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAD2/Aligned.sortedByCoord.out.markdup.bam \
    processed/KAE1/Aligned.sortedByCoord.out.markdup.bam





