

nice sambamba flagstat data/RNA/alignments/AAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAB1.txt
nice sambamba flagstat data/RNA/alignments/AAB2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAB2-new.txt
nice sambamba flagstat data/RNA/alignments/AAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAB2.txt
nice sambamba flagstat data/RNA/alignments/AAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAC1.txt
nice sambamba flagstat data/RNA/alignments/AAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAC2.txt
nice sambamba flagstat data/RNA/alignments/AAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAD1.txt
nice sambamba flagstat data/RNA/alignments/AAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAD2.txt
nice sambamba flagstat data/RNA/alignments/AAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAF1.txt
nice sambamba flagstat data/RNA/alignments/AAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAF2.txt
nice sambamba flagstat data/RNA/alignments/AAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAG1.txt
nice sambamba flagstat data/RNA/alignments/AAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAG2.txt
nice sambamba flagstat data/RNA/alignments/AAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAJ1.txt
nice sambamba flagstat data/RNA/alignments/AAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAJ2.txt
nice sambamba flagstat data/RNA/alignments/AAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAL1.txt
nice sambamba flagstat data/RNA/alignments/AAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAL2.txt
nice sambamba flagstat data/RNA/alignments/AAM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAM1.txt
nice sambamba flagstat data/RNA/alignments/AAM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAM2.txt
nice sambamba flagstat data/RNA/alignments/AAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAN1.txt
nice sambamba flagstat data/RNA/alignments/AAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAN2.txt
nice sambamba flagstat data/RNA/alignments/AAP1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAP1-new.txt
nice sambamba flagstat data/RNA/alignments/AAP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAP1.txt
nice sambamba flagstat data/RNA/alignments/AAP2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAP2.txt
nice sambamba flagstat data/RNA/alignments/AAS1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAS1.txt
nice sambamba flagstat data/RNA/alignments/AAS2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAS2.txt
nice sambamba flagstat data/RNA/alignments/AAT1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAT1.txt
nice sambamba flagstat data/RNA/alignments/AAT2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAT2.txt
nice sambamba flagstat data/RNA/alignments/AAU1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAU1.txt
nice sambamba flagstat data/RNA/alignments/AAU2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAU2.txt
nice sambamba flagstat data/RNA/alignments/AAV1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAV1.txt
nice sambamba flagstat data/RNA/alignments/AAV2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAV2.txt
nice sambamba flagstat data/RNA/alignments/AAW1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAW1.txt
nice sambamba flagstat data/RNA/alignments/AAW2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAW2.txt
nice sambamba flagstat data/RNA/alignments/AAX1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAX1.txt
nice sambamba flagstat data/RNA/alignments/AAX2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAX2.txt
nice sambamba flagstat data/RNA/alignments/AAY1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAY1.txt
nice sambamba flagstat data/RNA/alignments/AAY2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AAY2.txt
nice sambamba flagstat data/RNA/alignments/ABA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ABA1.txt
nice sambamba flagstat data/RNA/alignments/ABA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ABA2.txt
nice sambamba flagstat data/RNA/alignments/ACA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ACA1.txt
nice sambamba flagstat data/RNA/alignments/ACA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ACA2.txt
nice sambamba flagstat data/RNA/alignments/ADA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ADA1.txt
nice sambamba flagstat data/RNA/alignments/ADA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ADA2.txt
nice sambamba flagstat data/RNA/alignments/AFA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AFA1.txt
nice sambamba flagstat data/RNA/alignments/AFA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AFA2.txt
nice sambamba flagstat data/RNA/alignments/AHA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AHA1.txt
nice sambamba flagstat data/RNA/alignments/AHA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AHA2.txt
nice sambamba flagstat data/RNA/alignments/AIA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AIA1.txt
nice sambamba flagstat data/RNA/alignments/AIA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AIA2.txt
nice sambamba flagstat data/RNA/alignments/AKA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AKA1.txt
nice sambamba flagstat data/RNA/alignments/AKA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AKA2.txt
nice sambamba flagstat data/RNA/alignments/ALA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ALA1.txt
nice sambamba flagstat data/RNA/alignments/ALA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ALA2.txt
nice sambamba flagstat data/RNA/alignments/AMA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AMA1.txt
nice sambamba flagstat data/RNA/alignments/AMA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AMA2.txt
nice sambamba flagstat data/RNA/alignments/AOA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AOA1.txt
nice sambamba flagstat data/RNA/alignments/AOA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AOA2.txt
nice sambamba flagstat data/RNA/alignments/AQA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AQA1.txt
nice sambamba flagstat data/RNA/alignments/AQA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AQA2.txt
nice sambamba flagstat data/RNA/alignments/AZA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZA1.txt
nice sambamba flagstat data/RNA/alignments/AZA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZA2.txt
nice sambamba flagstat data/RNA/alignments/AZB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZB1.txt
nice sambamba flagstat data/RNA/alignments/AZB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZB2.txt
nice sambamba flagstat data/RNA/alignments/AZC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZC1.txt
nice sambamba flagstat data/RNA/alignments/AZC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZC2.txt
nice sambamba flagstat data/RNA/alignments/AZD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZD1.txt
nice sambamba flagstat data/RNA/alignments/AZD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZD2.txt
nice sambamba flagstat data/RNA/alignments/AZE1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZE1-new.txt
nice sambamba flagstat data/RNA/alignments/AZE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZE1.txt
nice sambamba flagstat data/RNA/alignments/AZE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZE2.txt
nice sambamba flagstat data/RNA/alignments/AZF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZF1.txt
nice sambamba flagstat data/RNA/alignments/AZF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZF2.txt
nice sambamba flagstat data/RNA/alignments/AZG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZG1.txt
nice sambamba flagstat data/RNA/alignments/AZG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZG2.txt
nice sambamba flagstat data/RNA/alignments/AZH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZH1.txt
nice sambamba flagstat data/RNA/alignments/AZH2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZH2-new.txt
nice sambamba flagstat data/RNA/alignments/AZH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/AZH2.txt
nice sambamba flagstat data/RNA/alignments/BAA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAA1.txt
nice sambamba flagstat data/RNA/alignments/BAA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAA2.txt
nice sambamba flagstat data/RNA/alignments/BAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAB1.txt
nice sambamba flagstat data/RNA/alignments/BAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAB2.txt
nice sambamba flagstat data/RNA/alignments/BAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAC1.txt
nice sambamba flagstat data/RNA/alignments/BAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAC2.txt
nice sambamba flagstat data/RNA/alignments/BAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAD1.txt
nice sambamba flagstat data/RNA/alignments/BAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAD2.txt
nice sambamba flagstat data/RNA/alignments/BAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAE1.txt
nice sambamba flagstat data/RNA/alignments/BAE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAE2.txt
nice sambamba flagstat data/RNA/alignments/BAH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAH1.txt
nice sambamba flagstat data/RNA/alignments/BAH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAH2.txt
nice sambamba flagstat data/RNA/alignments/BAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAI1.txt
nice sambamba flagstat data/RNA/alignments/BAI2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAI2-new.txt
nice sambamba flagstat data/RNA/alignments/BAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAI2.txt
nice sambamba flagstat data/RNA/alignments/BAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAJ1.txt
nice sambamba flagstat data/RNA/alignments/BAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAJ2.txt
nice sambamba flagstat data/RNA/alignments/BAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAK1.txt
nice sambamba flagstat data/RNA/alignments/BAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAK2.txt
nice sambamba flagstat data/RNA/alignments/BAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAL1.txt
nice sambamba flagstat data/RNA/alignments/BAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAL2.txt
nice sambamba flagstat data/RNA/alignments/BAM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAM1.txt
nice sambamba flagstat data/RNA/alignments/BAM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAM2.txt
nice sambamba flagstat data/RNA/alignments/BAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAN1.txt
nice sambamba flagstat data/RNA/alignments/BAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAN2.txt
nice sambamba flagstat data/RNA/alignments/BAO1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAO1.txt
nice sambamba flagstat data/RNA/alignments/BAO2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAO2.txt
nice sambamba flagstat data/RNA/alignments/BAR1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAR1.txt
nice sambamba flagstat data/RNA/alignments/BAR2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAR2.txt
nice sambamba flagstat data/RNA/alignments/BAS1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAS1.txt
nice sambamba flagstat data/RNA/alignments/BAS2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAS2.txt
nice sambamba flagstat data/RNA/alignments/BAT1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAT1.txt
nice sambamba flagstat data/RNA/alignments/BAT2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAT2-new.txt
nice sambamba flagstat data/RNA/alignments/BAT2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAT2.txt
nice sambamba flagstat data/RNA/alignments/BAU1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAU1.txt
nice sambamba flagstat data/RNA/alignments/BAU2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAU2.txt
nice sambamba flagstat data/RNA/alignments/BAW1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAW1.txt
nice sambamba flagstat data/RNA/alignments/BAW2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAW2.txt
nice sambamba flagstat data/RNA/alignments/BAX1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAX1.txt
nice sambamba flagstat data/RNA/alignments/BAX2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAX2.txt
nice sambamba flagstat data/RNA/alignments/BAY1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAY1.txt
nice sambamba flagstat data/RNA/alignments/BAY2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAY2-new.txt
nice sambamba flagstat data/RNA/alignments/BAY2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/BAY2.txt
nice sambamba flagstat data/RNA/alignments/CAC1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAC1-new.txt
nice sambamba flagstat data/RNA/alignments/CAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAC1.txt
nice sambamba flagstat data/RNA/alignments/CAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAC2.txt
nice sambamba flagstat data/RNA/alignments/CAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAD1.txt
nice sambamba flagstat data/RNA/alignments/CAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAD2.txt
nice sambamba flagstat data/RNA/alignments/CAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAF1.txt
nice sambamba flagstat data/RNA/alignments/CAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAF2.txt
nice sambamba flagstat data/RNA/alignments/CAO1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAO1-new.txt
nice sambamba flagstat data/RNA/alignments/CAO1-replicate/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAO1-replicate.txt
nice sambamba flagstat data/RNA/alignments/CAO1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAO1.txt
nice sambamba flagstat data/RNA/alignments/CAO2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAO2.txt
nice sambamba flagstat data/RNA/alignments/CAV1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAV1-new.txt
nice sambamba flagstat data/RNA/alignments/CAV1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAV1.txt
nice sambamba flagstat data/RNA/alignments/CAV2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CAV2.txt
nice sambamba flagstat data/RNA/alignments/CBA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBA1.txt
nice sambamba flagstat data/RNA/alignments/CBA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBA2.txt
nice sambamba flagstat data/RNA/alignments/CBE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBE1.txt
nice sambamba flagstat data/RNA/alignments/CBE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBE2.txt
nice sambamba flagstat data/RNA/alignments/CBG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBG1.txt
nice sambamba flagstat data/RNA/alignments/CBG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBG2.txt
nice sambamba flagstat data/RNA/alignments/CBH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBH1.txt
nice sambamba flagstat data/RNA/alignments/CBH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBH2.txt
nice sambamba flagstat data/RNA/alignments/CBI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBI1.txt
nice sambamba flagstat data/RNA/alignments/CBI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBI2.txt
nice sambamba flagstat data/RNA/alignments/CBM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBM1.txt
nice sambamba flagstat data/RNA/alignments/CBM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBM2.txt
nice sambamba flagstat data/RNA/alignments/CBP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBP1.txt
nice sambamba flagstat data/RNA/alignments/CBP2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBP2.txt
nice sambamba flagstat data/RNA/alignments/CBQ1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBQ1-new.txt
nice sambamba flagstat data/RNA/alignments/CBQ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBQ1.txt
nice sambamba flagstat data/RNA/alignments/CBQ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBQ2.txt
nice sambamba flagstat data/RNA/alignments/CBR1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBR1.txt
nice sambamba flagstat data/RNA/alignments/CBR2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBR2.txt
nice sambamba flagstat data/RNA/alignments/CBS1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBS1-new.txt
nice sambamba flagstat data/RNA/alignments/CBS1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBS1.txt
nice sambamba flagstat data/RNA/alignments/CBS2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBS2.txt
nice sambamba flagstat data/RNA/alignments/CBT1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBT1.txt
nice sambamba flagstat data/RNA/alignments/CBT2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBT2.txt
nice sambamba flagstat data/RNA/alignments/CBV1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBV1.txt
nice sambamba flagstat data/RNA/alignments/CBV2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CBV2.txt
nice sambamba flagstat data/RNA/alignments/CCD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCD1.txt
nice sambamba flagstat data/RNA/alignments/CCD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCD2.txt
nice sambamba flagstat data/RNA/alignments/CCW1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCW1.txt
nice sambamba flagstat data/RNA/alignments/CCW2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCW2.txt
nice sambamba flagstat data/RNA/alignments/CCZ1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCZ1-new.txt
nice sambamba flagstat data/RNA/alignments/CCZ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCZ1.txt
nice sambamba flagstat data/RNA/alignments/CCZ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CCZ2.txt
nice sambamba flagstat data/RNA/alignments/CDA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDA1.txt
nice sambamba flagstat data/RNA/alignments/CDA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDA2.txt
nice sambamba flagstat data/RNA/alignments/CDD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDD1.txt
nice sambamba flagstat data/RNA/alignments/CDD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDD2.txt
nice sambamba flagstat data/RNA/alignments/CDF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDF1.txt
nice sambamba flagstat data/RNA/alignments/CDF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDF2.txt
nice sambamba flagstat data/RNA/alignments/CDH1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDH1-new.txt
nice sambamba flagstat data/RNA/alignments/CDH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDH1.txt
nice sambamba flagstat data/RNA/alignments/CDH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/CDH2.txt
nice sambamba flagstat data/RNA/alignments/DAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAB1.txt
nice sambamba flagstat data/RNA/alignments/DAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAB2.txt
nice sambamba flagstat data/RNA/alignments/DAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAC1.txt
nice sambamba flagstat data/RNA/alignments/DAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAC2.txt
nice sambamba flagstat data/RNA/alignments/DAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAD1.txt
nice sambamba flagstat data/RNA/alignments/DAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/DAD2.txt
nice sambamba flagstat data/RNA/alignments/EAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAC1.txt
nice sambamba flagstat data/RNA/alignments/EAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAC2.txt
nice sambamba flagstat data/RNA/alignments/EAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAD1.txt
nice sambamba flagstat data/RNA/alignments/EAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAD2.txt
nice sambamba flagstat data/RNA/alignments/EAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAE1.txt
nice sambamba flagstat data/RNA/alignments/EAE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAE2.txt
nice sambamba flagstat data/RNA/alignments/EAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAF1.txt
nice sambamba flagstat data/RNA/alignments/EAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAF2.txt
nice sambamba flagstat data/RNA/alignments/EAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAG1.txt
nice sambamba flagstat data/RNA/alignments/EAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAG2.txt
nice sambamba flagstat data/RNA/alignments/EAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAI1.txt
nice sambamba flagstat data/RNA/alignments/EAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAI2.txt
nice sambamba flagstat data/RNA/alignments/EAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAJ1.txt
nice sambamba flagstat data/RNA/alignments/EAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAJ2.txt
nice sambamba flagstat data/RNA/alignments/EAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAK1.txt
nice sambamba flagstat data/RNA/alignments/EAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAK2.txt
nice sambamba flagstat data/RNA/alignments/EAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAL1.txt
nice sambamba flagstat data/RNA/alignments/EAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAL2.txt
nice sambamba flagstat data/RNA/alignments/EAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAN1.txt
nice sambamba flagstat data/RNA/alignments/EAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAN2.txt
nice sambamba flagstat data/RNA/alignments/EAO1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAO1.txt
nice sambamba flagstat data/RNA/alignments/EAO2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAO2.txt
nice sambamba flagstat data/RNA/alignments/EAP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAP1.txt
nice sambamba flagstat data/RNA/alignments/EAP2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAP2.txt
nice sambamba flagstat data/RNA/alignments/EAQ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAQ1.txt
nice sambamba flagstat data/RNA/alignments/EAQ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAQ2.txt
nice sambamba flagstat data/RNA/alignments/EAT1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAT1.txt
nice sambamba flagstat data/RNA/alignments/EAT2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAT2.txt
nice sambamba flagstat data/RNA/alignments/EAU1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAU1.txt
nice sambamba flagstat data/RNA/alignments/EAU2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAU2.txt
nice sambamba flagstat data/RNA/alignments/EAV1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAV1.txt
nice sambamba flagstat data/RNA/alignments/EAV2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAV2.txt
nice sambamba flagstat data/RNA/alignments/EAW1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAW1.txt
nice sambamba flagstat data/RNA/alignments/EAW2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAW2.txt
nice sambamba flagstat data/RNA/alignments/EAY1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAY1.txt
nice sambamba flagstat data/RNA/alignments/EAY2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAY2.txt
nice sambamba flagstat data/RNA/alignments/EAZ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAZ1.txt
nice sambamba flagstat data/RNA/alignments/EAZ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EAZ2.txt
nice sambamba flagstat data/RNA/alignments/EBB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBB1.txt
nice sambamba flagstat data/RNA/alignments/EBB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBB2.txt
nice sambamba flagstat data/RNA/alignments/EBC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBC1.txt
nice sambamba flagstat data/RNA/alignments/EBC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBC2.txt
nice sambamba flagstat data/RNA/alignments/EBD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBD1.txt
nice sambamba flagstat data/RNA/alignments/EBD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBD2.txt
nice sambamba flagstat data/RNA/alignments/EBF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBF1.txt
nice sambamba flagstat data/RNA/alignments/EBF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBF2.txt
nice sambamba flagstat data/RNA/alignments/EBG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBG1.txt
nice sambamba flagstat data/RNA/alignments/EBG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBG2.txt
nice sambamba flagstat data/RNA/alignments/EBH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBH1.txt
nice sambamba flagstat data/RNA/alignments/EBH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBH2.txt
nice sambamba flagstat data/RNA/alignments/EBK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBK1.txt
nice sambamba flagstat data/RNA/alignments/EBK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBK2.txt
nice sambamba flagstat data/RNA/alignments/EBL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBL1.txt
nice sambamba flagstat data/RNA/alignments/EBL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBL2.txt
nice sambamba flagstat data/RNA/alignments/EBM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBM1.txt
nice sambamba flagstat data/RNA/alignments/EBM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBM2.txt
nice sambamba flagstat data/RNA/alignments/EBN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBN1.txt
nice sambamba flagstat data/RNA/alignments/EBN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBN2.txt
nice sambamba flagstat data/RNA/alignments/EBO1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBO1.txt
nice sambamba flagstat data/RNA/alignments/EBO2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBO2.txt
nice sambamba flagstat data/RNA/alignments/EBP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBP1.txt
nice sambamba flagstat data/RNA/alignments/EBR1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBR1.txt
nice sambamba flagstat data/RNA/alignments/EBR2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBR2.txt
nice sambamba flagstat data/RNA/alignments/EBU1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBU1.txt
nice sambamba flagstat data/RNA/alignments/EBU2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBU2.txt
nice sambamba flagstat data/RNA/alignments/EBV1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBV1.txt
nice sambamba flagstat data/RNA/alignments/EBV2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBV2.txt
nice sambamba flagstat data/RNA/alignments/EBW1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBW1.txt
nice sambamba flagstat data/RNA/alignments/EBW2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBW2.txt
nice sambamba flagstat data/RNA/alignments/EBX1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBX1.txt
nice sambamba flagstat data/RNA/alignments/EBX2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBX2.txt
nice sambamba flagstat data/RNA/alignments/EBY1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBY1.txt
nice sambamba flagstat data/RNA/alignments/EBY2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/EBY2.txt
nice sambamba flagstat data/RNA/alignments/ECA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECA1.txt
nice sambamba flagstat data/RNA/alignments/ECA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECA2.txt
nice sambamba flagstat data/RNA/alignments/ECB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECB1.txt
nice sambamba flagstat data/RNA/alignments/ECB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECB2.txt
nice sambamba flagstat data/RNA/alignments/ECD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECD1.txt
nice sambamba flagstat data/RNA/alignments/ECD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECD2.txt
nice sambamba flagstat data/RNA/alignments/ECE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECE1.txt
nice sambamba flagstat data/RNA/alignments/ECE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECE2.txt
nice sambamba flagstat data/RNA/alignments/ECF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECF1.txt
nice sambamba flagstat data/RNA/alignments/ECF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECF2.txt
nice sambamba flagstat data/RNA/alignments/ECG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECG1.txt
nice sambamba flagstat data/RNA/alignments/ECG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECG2.txt
nice sambamba flagstat data/RNA/alignments/ECH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECH1.txt
nice sambamba flagstat data/RNA/alignments/ECH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECH2.txt
nice sambamba flagstat data/RNA/alignments/ECI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECI1.txt
nice sambamba flagstat data/RNA/alignments/ECI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECI2.txt
nice sambamba flagstat data/RNA/alignments/ECK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECK1.txt
nice sambamba flagstat data/RNA/alignments/ECK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECK2.txt
nice sambamba flagstat data/RNA/alignments/ECN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECN1.txt
nice sambamba flagstat data/RNA/alignments/ECN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/ECN2.txt
nice sambamba flagstat data/RNA/alignments/FAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAB1.txt
nice sambamba flagstat data/RNA/alignments/FAB2-replicate/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAB2-replicate.txt
nice sambamba flagstat data/RNA/alignments/FAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAB2.txt
nice sambamba flagstat data/RNA/alignments/FAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAD1.txt
nice sambamba flagstat data/RNA/alignments/FAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAD2.txt
nice sambamba flagstat data/RNA/alignments/FAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAF1.txt
nice sambamba flagstat data/RNA/alignments/FAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAF2.txt
nice sambamba flagstat data/RNA/alignments/FAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAG1.txt
nice sambamba flagstat data/RNA/alignments/FAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAG2.txt
nice sambamba flagstat data/RNA/alignments/FAH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAH2.txt
nice sambamba flagstat data/RNA/alignments/FAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAI1.txt
nice sambamba flagstat data/RNA/alignments/FAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAI2.txt
nice sambamba flagstat data/RNA/alignments/FAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAJ1.txt
nice sambamba flagstat data/RNA/alignments/FAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAJ2.txt
nice sambamba flagstat data/RNA/alignments/FAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAK1.txt
nice sambamba flagstat data/RNA/alignments/FAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAK2.txt
nice sambamba flagstat data/RNA/alignments/FAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAL1.txt
nice sambamba flagstat data/RNA/alignments/FAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAL2.txt
nice sambamba flagstat data/RNA/alignments/FAM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAM1.txt
nice sambamba flagstat data/RNA/alignments/FAM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAM2.txt
nice sambamba flagstat data/RNA/alignments/FAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAN1.txt
nice sambamba flagstat data/RNA/alignments/FAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAN2.txt
nice sambamba flagstat data/RNA/alignments/FAP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAP1.txt
nice sambamba flagstat data/RNA/alignments/FAP2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAP2.txt
nice sambamba flagstat data/RNA/alignments/FAQ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAQ1.txt
nice sambamba flagstat data/RNA/alignments/FAQ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/FAQ2.txt
nice sambamba flagstat data/RNA/alignments/GAA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAA1.txt
nice sambamba flagstat data/RNA/alignments/GAA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAA2.txt
nice sambamba flagstat data/RNA/alignments/GAE1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAE1-new.txt
nice sambamba flagstat data/RNA/alignments/GAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAE1.txt
nice sambamba flagstat data/RNA/alignments/GAE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAE2.txt
nice sambamba flagstat data/RNA/alignments/GAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAG1.txt
nice sambamba flagstat data/RNA/alignments/GAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAG2.txt
nice sambamba flagstat data/RNA/alignments/GAH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAH1.txt
nice sambamba flagstat data/RNA/alignments/GAH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAH2.txt
nice sambamba flagstat data/RNA/alignments/GAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAI1.txt
nice sambamba flagstat data/RNA/alignments/GAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAI2.txt
nice sambamba flagstat data/RNA/alignments/GAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAJ1.txt
nice sambamba flagstat data/RNA/alignments/GAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAJ2.txt
nice sambamba flagstat data/RNA/alignments/GAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAK1.txt
nice sambamba flagstat data/RNA/alignments/GAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAK2.txt
nice sambamba flagstat data/RNA/alignments/GAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAL1.txt
nice sambamba flagstat data/RNA/alignments/GAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAL2.txt
nice sambamba flagstat data/RNA/alignments/GAM1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAM1-new.txt
nice sambamba flagstat data/RNA/alignments/GAM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAM1.txt
nice sambamba flagstat data/RNA/alignments/GAM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAM2.txt
nice sambamba flagstat data/RNA/alignments/GAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAN1.txt
nice sambamba flagstat data/RNA/alignments/GAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAN2.txt
nice sambamba flagstat data/RNA/alignments/GAO1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAO1.txt
nice sambamba flagstat data/RNA/alignments/GAO2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAO2-new.txt
nice sambamba flagstat data/RNA/alignments/GAO2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAO2.txt
nice sambamba flagstat data/RNA/alignments/GAP1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAP1.txt
nice sambamba flagstat data/RNA/alignments/GAP2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAP2.txt
nice sambamba flagstat data/RNA/alignments/GAQ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAQ1.txt
nice sambamba flagstat data/RNA/alignments/GAQ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAQ2.txt
nice sambamba flagstat data/RNA/alignments/GAR1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAR1.txt
nice sambamba flagstat data/RNA/alignments/GAR2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAR2.txt
nice sambamba flagstat data/RNA/alignments/GAS1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAS1-new.txt
nice sambamba flagstat data/RNA/alignments/GAS1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAS1.txt
nice sambamba flagstat data/RNA/alignments/GAS2-replicate/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAS2-replicate.txt
nice sambamba flagstat data/RNA/alignments/GAS2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/GAS2.txt
nice sambamba flagstat data/RNA/alignments/HAA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAA1.txt
nice sambamba flagstat data/RNA/alignments/HAA2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAA2-new.txt
nice sambamba flagstat data/RNA/alignments/HAA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAA2.txt
nice sambamba flagstat data/RNA/alignments/HAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAB1.txt
nice sambamba flagstat data/RNA/alignments/HAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAB2.txt
nice sambamba flagstat data/RNA/alignments/HAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAC1.txt
nice sambamba flagstat data/RNA/alignments/HAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAC2.txt
nice sambamba flagstat data/RNA/alignments/HAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAD1.txt
nice sambamba flagstat data/RNA/alignments/HAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAD2.txt
nice sambamba flagstat data/RNA/alignments/HAE1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAE1-new.txt
nice sambamba flagstat data/RNA/alignments/HAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAE1.txt
nice sambamba flagstat data/RNA/alignments/HAE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAE2.txt
nice sambamba flagstat data/RNA/alignments/HAF1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAF1-new.txt
nice sambamba flagstat data/RNA/alignments/HAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAF1.txt
nice sambamba flagstat data/RNA/alignments/HAF2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAF2-new.txt
nice sambamba flagstat data/RNA/alignments/HAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAF2.txt
nice sambamba flagstat data/RNA/alignments/HAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAG1.txt
nice sambamba flagstat data/RNA/alignments/HAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAG2.txt
nice sambamba flagstat data/RNA/alignments/HAH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAH1.txt
nice sambamba flagstat data/RNA/alignments/HAH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAH2.txt
nice sambamba flagstat data/RNA/alignments/HAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAI1.txt
nice sambamba flagstat data/RNA/alignments/HAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAI2.txt
nice sambamba flagstat data/RNA/alignments/HAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAK1.txt
nice sambamba flagstat data/RNA/alignments/HAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/HAK2.txt
nice sambamba flagstat data/RNA/alignments/JAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAB1.txt
nice sambamba flagstat data/RNA/alignments/JAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAB2.txt
nice sambamba flagstat data/RNA/alignments/JAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAC1.txt
nice sambamba flagstat data/RNA/alignments/JAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAC2.txt
nice sambamba flagstat data/RNA/alignments/JAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAD1.txt
nice sambamba flagstat data/RNA/alignments/JAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAD2.txt
nice sambamba flagstat data/RNA/alignments/JAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAE1.txt
nice sambamba flagstat data/RNA/alignments/JAE2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAE2.txt
nice sambamba flagstat data/RNA/alignments/JAF1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAF1.txt
nice sambamba flagstat data/RNA/alignments/JAF2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAF2.txt
nice sambamba flagstat data/RNA/alignments/JAG1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAG1.txt
nice sambamba flagstat data/RNA/alignments/JAG2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAG2.txt
nice sambamba flagstat data/RNA/alignments/JAH1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAH1.txt
nice sambamba flagstat data/RNA/alignments/JAH2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAH2.txt
nice sambamba flagstat data/RNA/alignments/JAI1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAI1.txt
nice sambamba flagstat data/RNA/alignments/JAI2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAI2.txt
nice sambamba flagstat data/RNA/alignments/JAJ1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAJ1.txt
nice sambamba flagstat data/RNA/alignments/JAJ2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAJ2.txt
nice sambamba flagstat data/RNA/alignments/JAK1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAK1.txt
nice sambamba flagstat data/RNA/alignments/JAK2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAK2.txt
nice sambamba flagstat data/RNA/alignments/JAL1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAL1.txt
nice sambamba flagstat data/RNA/alignments/JAL2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAL2.txt
nice sambamba flagstat data/RNA/alignments/JAM1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAM1.txt
nice sambamba flagstat data/RNA/alignments/JAM2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAM2.txt
nice sambamba flagstat data/RNA/alignments/JAN1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAN1-new.txt
nice sambamba flagstat data/RNA/alignments/JAN1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAN1.txt
nice sambamba flagstat data/RNA/alignments/JAN2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/JAN2.txt
nice sambamba flagstat data/RNA/alignments/KAA1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAA1-new.txt
nice sambamba flagstat data/RNA/alignments/KAA1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAA1.txt
nice sambamba flagstat data/RNA/alignments/KAA2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAA2.txt
nice sambamba flagstat data/RNA/alignments/KAB1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAB1.txt
nice sambamba flagstat data/RNA/alignments/KAB2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAB2.txt
nice sambamba flagstat data/RNA/alignments/KAC1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAC1-new.txt
nice sambamba flagstat data/RNA/alignments/KAC1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAC1.txt
nice sambamba flagstat data/RNA/alignments/KAC2-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAC2-new.txt
nice sambamba flagstat data/RNA/alignments/KAC2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAC2.txt
nice sambamba flagstat data/RNA/alignments/KAD1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAD1.txt
nice sambamba flagstat data/RNA/alignments/KAD2/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAD2.txt
nice sambamba flagstat data/RNA/alignments/KAE1-new/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAE1-new.txt
nice sambamba flagstat data/RNA/alignments/KAE1/Aligned.sortedByCoord.out.markdup.bam > output/tables/flagstat/KAE1.txt
