data/RNA/alignments/AAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAP2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAS1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAS2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAT1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAT2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAU1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAU2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAV1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAV2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAW1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAW2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAX1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAX2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAY1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AAY2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ABA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ABA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ACA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ACA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ADA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ADA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AFA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AFA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AHA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AHA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AIA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AIA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AKA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AKA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ALA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ALA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AMA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AMA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AOA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AOA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AQA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AQA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/AZH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAO1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAO2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAR1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAR2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAS1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAS2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAT1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAT2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAU1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAU2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAW1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAW2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAX1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAX2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAY1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/BAY2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAO1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAO1-replicate/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAO2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAV1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CAV2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBP2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBQ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBQ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBR1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBR2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBS1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBS2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBT1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBT2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBV1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CBV2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCW1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCW2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCZ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CCZ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/CDH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/DAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAO1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAO2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAP2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAQ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAQ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAT1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAT2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAU1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAU2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAV1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAV2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAW1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAW2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAY1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAY2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAZ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EAZ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBO1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBO2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBR1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBR2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBU1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBU2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBV1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBV2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBW1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBW2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBX1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBX2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBY1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/EBY2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/ECN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAB2-replicate/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAP2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAQ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/FAQ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAO1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAO2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAP1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAP2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAQ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAQ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAR1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAR2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAS1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAS2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/GAS2-replicate/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/HAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAE1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAE2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAF1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAF2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAG1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAG2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAH1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAH2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAI1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAI2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAJ1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAJ2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAK1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAK2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAL1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAL2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAM1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAM2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAN1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/JAN2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAA1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAA2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAB1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAB2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAC1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAC2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAD1/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAD2/Aligned.sortedByCoord.out.markdup.bam
data/RNA/alignments/KAE1/Aligned.sortedByCoord.out.markdup.bam
