#nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAB1/Aligned.sortedByCoord.out.bam processed/AAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAB2/Aligned.sortedByCoord.out.bam processed/AAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAC1/Aligned.sortedByCoord.out.bam processed/AAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAC2/Aligned.sortedByCoord.out.bam processed/AAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAD1/Aligned.sortedByCoord.out.bam processed/AAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAD2/Aligned.sortedByCoord.out.bam processed/AAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAF1/Aligned.sortedByCoord.out.bam processed/AAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAF2/Aligned.sortedByCoord.out.bam processed/AAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAG1/Aligned.sortedByCoord.out.bam processed/AAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAG2/Aligned.sortedByCoord.out.bam processed/AAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAJ1/Aligned.sortedByCoord.out.bam processed/AAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAJ2/Aligned.sortedByCoord.out.bam processed/AAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAL1/Aligned.sortedByCoord.out.bam processed/AAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAL2/Aligned.sortedByCoord.out.bam processed/AAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAM1/Aligned.sortedByCoord.out.bam processed/AAM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAM2/Aligned.sortedByCoord.out.bam processed/AAM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAN1/Aligned.sortedByCoord.out.bam processed/AAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAN2/Aligned.sortedByCoord.out.bam processed/AAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAP1/Aligned.sortedByCoord.out.bam processed/AAP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAP2/Aligned.sortedByCoord.out.bam processed/AAP2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAS1/Aligned.sortedByCoord.out.bam processed/AAS1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAS2/Aligned.sortedByCoord.out.bam processed/AAS2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAT1/Aligned.sortedByCoord.out.bam processed/AAT1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAT2/Aligned.sortedByCoord.out.bam processed/AAT2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAU1/Aligned.sortedByCoord.out.bam processed/AAU1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAU2/Aligned.sortedByCoord.out.bam processed/AAU2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAV1/Aligned.sortedByCoord.out.bam processed/AAV1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAV2/Aligned.sortedByCoord.out.bam processed/AAV2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAW1/Aligned.sortedByCoord.out.bam processed/AAW1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAW2/Aligned.sortedByCoord.out.bam processed/AAW2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAX1/Aligned.sortedByCoord.out.bam processed/AAX1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAX2/Aligned.sortedByCoord.out.bam processed/AAX2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAY1/Aligned.sortedByCoord.out.bam processed/AAY1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AAY2/Aligned.sortedByCoord.out.bam processed/AAY2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ABA1/Aligned.sortedByCoord.out.bam processed/ABA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ABA2/Aligned.sortedByCoord.out.bam processed/ABA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ACA1/Aligned.sortedByCoord.out.bam processed/ACA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ACA2/Aligned.sortedByCoord.out.bam processed/ACA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ADA1/Aligned.sortedByCoord.out.bam processed/ADA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ADA2/Aligned.sortedByCoord.out.bam processed/ADA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AFA1/Aligned.sortedByCoord.out.bam processed/AFA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AFA2/Aligned.sortedByCoord.out.bam processed/AFA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AHA1/Aligned.sortedByCoord.out.bam processed/AHA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AHA2/Aligned.sortedByCoord.out.bam processed/AHA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AIA1/Aligned.sortedByCoord.out.bam processed/AIA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AIA2/Aligned.sortedByCoord.out.bam processed/AIA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AKA1/Aligned.sortedByCoord.out.bam processed/AKA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AKA2/Aligned.sortedByCoord.out.bam processed/AKA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ALA1/Aligned.sortedByCoord.out.bam processed/ALA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ALA2/Aligned.sortedByCoord.out.bam processed/ALA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AMA1/Aligned.sortedByCoord.out.bam processed/AMA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AMA2/Aligned.sortedByCoord.out.bam processed/AMA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AOA1/Aligned.sortedByCoord.out.bam processed/AOA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AOA2/Aligned.sortedByCoord.out.bam processed/AOA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AQA1/Aligned.sortedByCoord.out.bam processed/AQA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AQA2/Aligned.sortedByCoord.out.bam processed/AQA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZA1/Aligned.sortedByCoord.out.bam processed/AZA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZA2/Aligned.sortedByCoord.out.bam processed/AZA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZB1/Aligned.sortedByCoord.out.bam processed/AZB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZB2/Aligned.sortedByCoord.out.bam processed/AZB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZC1/Aligned.sortedByCoord.out.bam processed/AZC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZC2/Aligned.sortedByCoord.out.bam processed/AZC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZD1/Aligned.sortedByCoord.out.bam processed/AZD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZD2/Aligned.sortedByCoord.out.bam processed/AZD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZE1/Aligned.sortedByCoord.out.bam processed/AZE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZE2/Aligned.sortedByCoord.out.bam processed/AZE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZF1/Aligned.sortedByCoord.out.bam processed/AZF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZF2/Aligned.sortedByCoord.out.bam processed/AZF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZG1/Aligned.sortedByCoord.out.bam processed/AZG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZG2/Aligned.sortedByCoord.out.bam processed/AZG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZH1/Aligned.sortedByCoord.out.bam processed/AZH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/AZH2/Aligned.sortedByCoord.out.bam processed/AZH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAA1/Aligned.sortedByCoord.out.bam processed/BAA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAA2/Aligned.sortedByCoord.out.bam processed/BAA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAB1/Aligned.sortedByCoord.out.bam processed/BAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAB2/Aligned.sortedByCoord.out.bam processed/BAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAC1/Aligned.sortedByCoord.out.bam processed/BAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAC2/Aligned.sortedByCoord.out.bam processed/BAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAD1/Aligned.sortedByCoord.out.bam processed/BAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAD2/Aligned.sortedByCoord.out.bam processed/BAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAE1/Aligned.sortedByCoord.out.bam processed/BAE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAE2/Aligned.sortedByCoord.out.bam processed/BAE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAH1/Aligned.sortedByCoord.out.bam processed/BAH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAH2/Aligned.sortedByCoord.out.bam processed/BAH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAI1/Aligned.sortedByCoord.out.bam processed/BAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAI2/Aligned.sortedByCoord.out.bam processed/BAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAJ1/Aligned.sortedByCoord.out.bam processed/BAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAJ2/Aligned.sortedByCoord.out.bam processed/BAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAK1/Aligned.sortedByCoord.out.bam processed/BAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAK2/Aligned.sortedByCoord.out.bam processed/BAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAL1/Aligned.sortedByCoord.out.bam processed/BAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAL2/Aligned.sortedByCoord.out.bam processed/BAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAM1/Aligned.sortedByCoord.out.bam processed/BAM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAM2/Aligned.sortedByCoord.out.bam processed/BAM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAN1/Aligned.sortedByCoord.out.bam processed/BAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAN2/Aligned.sortedByCoord.out.bam processed/BAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAO1/Aligned.sortedByCoord.out.bam processed/BAO1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAO2/Aligned.sortedByCoord.out.bam processed/BAO2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAR1/Aligned.sortedByCoord.out.bam processed/BAR1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAR2/Aligned.sortedByCoord.out.bam processed/BAR2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAS1/Aligned.sortedByCoord.out.bam processed/BAS1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAS2/Aligned.sortedByCoord.out.bam processed/BAS2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAT1/Aligned.sortedByCoord.out.bam processed/BAT1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAT2/Aligned.sortedByCoord.out.bam processed/BAT2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAU1/Aligned.sortedByCoord.out.bam processed/BAU1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAU2/Aligned.sortedByCoord.out.bam processed/BAU2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAW1/Aligned.sortedByCoord.out.bam processed/BAW1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAW2/Aligned.sortedByCoord.out.bam processed/BAW2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAX1/Aligned.sortedByCoord.out.bam processed/BAX1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAX2/Aligned.sortedByCoord.out.bam processed/BAX2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAY1/Aligned.sortedByCoord.out.bam processed/BAY1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/BAY2/Aligned.sortedByCoord.out.bam processed/BAY2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAC1/Aligned.sortedByCoord.out.bam processed/CAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAC2/Aligned.sortedByCoord.out.bam processed/CAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAD1/Aligned.sortedByCoord.out.bam processed/CAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAD2/Aligned.sortedByCoord.out.bam processed/CAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAF1/Aligned.sortedByCoord.out.bam processed/CAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAF2/Aligned.sortedByCoord.out.bam processed/CAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAO1-replicate/Aligned.sortedByCoord.out.bam processed/CAO1-replicate/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAO1/Aligned.sortedByCoord.out.bam processed/CAO1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAO2/Aligned.sortedByCoord.out.bam processed/CAO2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAV1/Aligned.sortedByCoord.out.bam processed/CAV1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CAV2/Aligned.sortedByCoord.out.bam processed/CAV2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBA1/Aligned.sortedByCoord.out.bam processed/CBA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBA2/Aligned.sortedByCoord.out.bam processed/CBA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBE1/Aligned.sortedByCoord.out.bam processed/CBE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBE2/Aligned.sortedByCoord.out.bam processed/CBE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBG1/Aligned.sortedByCoord.out.bam processed/CBG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBG2/Aligned.sortedByCoord.out.bam processed/CBG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBH1/Aligned.sortedByCoord.out.bam processed/CBH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBH2/Aligned.sortedByCoord.out.bam processed/CBH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBI1/Aligned.sortedByCoord.out.bam processed/CBI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBI2/Aligned.sortedByCoord.out.bam processed/CBI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBM1/Aligned.sortedByCoord.out.bam processed/CBM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBM2/Aligned.sortedByCoord.out.bam processed/CBM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBP1/Aligned.sortedByCoord.out.bam processed/CBP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBP2/Aligned.sortedByCoord.out.bam processed/CBP2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBQ1/Aligned.sortedByCoord.out.bam processed/CBQ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBQ2/Aligned.sortedByCoord.out.bam processed/CBQ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBR1/Aligned.sortedByCoord.out.bam processed/CBR1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBR2/Aligned.sortedByCoord.out.bam processed/CBR2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBS1/Aligned.sortedByCoord.out.bam processed/CBS1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBS2/Aligned.sortedByCoord.out.bam processed/CBS2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBT1/Aligned.sortedByCoord.out.bam processed/CBT1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBT2/Aligned.sortedByCoord.out.bam processed/CBT2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBV1/Aligned.sortedByCoord.out.bam processed/CBV1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CBV2/Aligned.sortedByCoord.out.bam processed/CBV2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCD1/Aligned.sortedByCoord.out.bam processed/CCD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCD2/Aligned.sortedByCoord.out.bam processed/CCD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCW1/Aligned.sortedByCoord.out.bam processed/CCW1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCW2/Aligned.sortedByCoord.out.bam processed/CCW2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCZ1/Aligned.sortedByCoord.out.bam processed/CCZ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CCZ2/Aligned.sortedByCoord.out.bam processed/CCZ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDA1/Aligned.sortedByCoord.out.bam processed/CDA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDA2/Aligned.sortedByCoord.out.bam processed/CDA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDD1/Aligned.sortedByCoord.out.bam processed/CDD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDD2/Aligned.sortedByCoord.out.bam processed/CDD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDF1/Aligned.sortedByCoord.out.bam processed/CDF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDF2/Aligned.sortedByCoord.out.bam processed/CDF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDH1/Aligned.sortedByCoord.out.bam processed/CDH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/CDH2/Aligned.sortedByCoord.out.bam processed/CDH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAB1/Aligned.sortedByCoord.out.bam processed/DAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAB2/Aligned.sortedByCoord.out.bam processed/DAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAC1/Aligned.sortedByCoord.out.bam processed/DAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAC2/Aligned.sortedByCoord.out.bam processed/DAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAD1/Aligned.sortedByCoord.out.bam processed/DAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/DAD2/Aligned.sortedByCoord.out.bam processed/DAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAC1/Aligned.sortedByCoord.out.bam processed/EAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAC2/Aligned.sortedByCoord.out.bam processed/EAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAD1/Aligned.sortedByCoord.out.bam processed/EAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAD2/Aligned.sortedByCoord.out.bam processed/EAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAE1/Aligned.sortedByCoord.out.bam processed/EAE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAE2/Aligned.sortedByCoord.out.bam processed/EAE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAF1/Aligned.sortedByCoord.out.bam processed/EAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAF2/Aligned.sortedByCoord.out.bam processed/EAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAG1/Aligned.sortedByCoord.out.bam processed/EAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAG2/Aligned.sortedByCoord.out.bam processed/EAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAI1/Aligned.sortedByCoord.out.bam processed/EAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAI2/Aligned.sortedByCoord.out.bam processed/EAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAJ1/Aligned.sortedByCoord.out.bam processed/EAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAJ2/Aligned.sortedByCoord.out.bam processed/EAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAK1/Aligned.sortedByCoord.out.bam processed/EAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAK2/Aligned.sortedByCoord.out.bam processed/EAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAL1/Aligned.sortedByCoord.out.bam processed/EAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAL2/Aligned.sortedByCoord.out.bam processed/EAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAN1/Aligned.sortedByCoord.out.bam processed/EAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAN2/Aligned.sortedByCoord.out.bam processed/EAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAO1/Aligned.sortedByCoord.out.bam processed/EAO1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAO2/Aligned.sortedByCoord.out.bam processed/EAO2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAP1/Aligned.sortedByCoord.out.bam processed/EAP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAP2/Aligned.sortedByCoord.out.bam processed/EAP2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAQ1/Aligned.sortedByCoord.out.bam processed/EAQ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAQ2/Aligned.sortedByCoord.out.bam processed/EAQ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAT1/Aligned.sortedByCoord.out.bam processed/EAT1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAT2/Aligned.sortedByCoord.out.bam processed/EAT2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAU1/Aligned.sortedByCoord.out.bam processed/EAU1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAU2/Aligned.sortedByCoord.out.bam processed/EAU2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAV1/Aligned.sortedByCoord.out.bam processed/EAV1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAV2/Aligned.sortedByCoord.out.bam processed/EAV2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAW1/Aligned.sortedByCoord.out.bam processed/EAW1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAW2/Aligned.sortedByCoord.out.bam processed/EAW2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAY1/Aligned.sortedByCoord.out.bam processed/EAY1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAY2/Aligned.sortedByCoord.out.bam processed/EAY2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAZ1/Aligned.sortedByCoord.out.bam processed/EAZ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EAZ2/Aligned.sortedByCoord.out.bam processed/EAZ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBB1/Aligned.sortedByCoord.out.bam processed/EBB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBB2/Aligned.sortedByCoord.out.bam processed/EBB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBC1/Aligned.sortedByCoord.out.bam processed/EBC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBC2/Aligned.sortedByCoord.out.bam processed/EBC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBD1/Aligned.sortedByCoord.out.bam processed/EBD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBD2/Aligned.sortedByCoord.out.bam processed/EBD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBF1/Aligned.sortedByCoord.out.bam processed/EBF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBF2/Aligned.sortedByCoord.out.bam processed/EBF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBG1/Aligned.sortedByCoord.out.bam processed/EBG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBG2/Aligned.sortedByCoord.out.bam processed/EBG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBH1/Aligned.sortedByCoord.out.bam processed/EBH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBH2/Aligned.sortedByCoord.out.bam processed/EBH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBK1/Aligned.sortedByCoord.out.bam processed/EBK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBK2/Aligned.sortedByCoord.out.bam processed/EBK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBL1/Aligned.sortedByCoord.out.bam processed/EBL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBL2/Aligned.sortedByCoord.out.bam processed/EBL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBM1/Aligned.sortedByCoord.out.bam processed/EBM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBM2/Aligned.sortedByCoord.out.bam processed/EBM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBN1/Aligned.sortedByCoord.out.bam processed/EBN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBN2/Aligned.sortedByCoord.out.bam processed/EBN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBO1/Aligned.sortedByCoord.out.bam processed/EBO1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBO2/Aligned.sortedByCoord.out.bam processed/EBO2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBP1/Aligned.sortedByCoord.out.bam processed/EBP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBR1/Aligned.sortedByCoord.out.bam processed/EBR1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBR2/Aligned.sortedByCoord.out.bam processed/EBR2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBU1/Aligned.sortedByCoord.out.bam processed/EBU1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBU2/Aligned.sortedByCoord.out.bam processed/EBU2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBV1/Aligned.sortedByCoord.out.bam processed/EBV1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBV2/Aligned.sortedByCoord.out.bam processed/EBV2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBW1/Aligned.sortedByCoord.out.bam processed/EBW1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBW2/Aligned.sortedByCoord.out.bam processed/EBW2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBX1/Aligned.sortedByCoord.out.bam processed/EBX1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBX2/Aligned.sortedByCoord.out.bam processed/EBX2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBY1/Aligned.sortedByCoord.out.bam processed/EBY1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/EBY2/Aligned.sortedByCoord.out.bam processed/EBY2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECA1/Aligned.sortedByCoord.out.bam processed/ECA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECA2/Aligned.sortedByCoord.out.bam processed/ECA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECB1/Aligned.sortedByCoord.out.bam processed/ECB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECB2/Aligned.sortedByCoord.out.bam processed/ECB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECD1/Aligned.sortedByCoord.out.bam processed/ECD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECD2/Aligned.sortedByCoord.out.bam processed/ECD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECE1/Aligned.sortedByCoord.out.bam processed/ECE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECE2/Aligned.sortedByCoord.out.bam processed/ECE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECF1/Aligned.sortedByCoord.out.bam processed/ECF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECF2/Aligned.sortedByCoord.out.bam processed/ECF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECG1/Aligned.sortedByCoord.out.bam processed/ECG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECG2/Aligned.sortedByCoord.out.bam processed/ECG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECH1/Aligned.sortedByCoord.out.bam processed/ECH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECH2/Aligned.sortedByCoord.out.bam processed/ECH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECI1/Aligned.sortedByCoord.out.bam processed/ECI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECI2/Aligned.sortedByCoord.out.bam processed/ECI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECK1/Aligned.sortedByCoord.out.bam processed/ECK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECK2/Aligned.sortedByCoord.out.bam processed/ECK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECN1/Aligned.sortedByCoord.out.bam processed/ECN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/ECN2/Aligned.sortedByCoord.out.bam processed/ECN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAB1/Aligned.sortedByCoord.out.bam processed/FAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAB2-replicate/Aligned.sortedByCoord.out.bam processed/FAB2-replicate/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAB2/Aligned.sortedByCoord.out.bam processed/FAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAD1/Aligned.sortedByCoord.out.bam processed/FAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAD2/Aligned.sortedByCoord.out.bam processed/FAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAF1/Aligned.sortedByCoord.out.bam processed/FAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAF2/Aligned.sortedByCoord.out.bam processed/FAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAG1/Aligned.sortedByCoord.out.bam processed/FAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAG2/Aligned.sortedByCoord.out.bam processed/FAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAH2/Aligned.sortedByCoord.out.bam processed/FAH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAI1/Aligned.sortedByCoord.out.bam processed/FAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAI2/Aligned.sortedByCoord.out.bam processed/FAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAJ1/Aligned.sortedByCoord.out.bam processed/FAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAJ2/Aligned.sortedByCoord.out.bam processed/FAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAK1/Aligned.sortedByCoord.out.bam processed/FAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAK2/Aligned.sortedByCoord.out.bam processed/FAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAL1/Aligned.sortedByCoord.out.bam processed/FAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAL2/Aligned.sortedByCoord.out.bam processed/FAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAM1/Aligned.sortedByCoord.out.bam processed/FAM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAM2/Aligned.sortedByCoord.out.bam processed/FAM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAN1/Aligned.sortedByCoord.out.bam processed/FAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAN2/Aligned.sortedByCoord.out.bam processed/FAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAP1/Aligned.sortedByCoord.out.bam processed/FAP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAP2/Aligned.sortedByCoord.out.bam processed/FAP2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAQ1/Aligned.sortedByCoord.out.bam processed/FAQ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/FAQ2/Aligned.sortedByCoord.out.bam processed/FAQ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAA1/Aligned.sortedByCoord.out.bam processed/GAA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAA2/Aligned.sortedByCoord.out.bam processed/GAA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAE1/Aligned.sortedByCoord.out.bam processed/GAE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAE2/Aligned.sortedByCoord.out.bam processed/GAE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAG1/Aligned.sortedByCoord.out.bam processed/GAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAG2/Aligned.sortedByCoord.out.bam processed/GAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAH1/Aligned.sortedByCoord.out.bam processed/GAH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAH2/Aligned.sortedByCoord.out.bam processed/GAH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAI1/Aligned.sortedByCoord.out.bam processed/GAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAI2/Aligned.sortedByCoord.out.bam processed/GAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAJ1/Aligned.sortedByCoord.out.bam processed/GAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAJ2/Aligned.sortedByCoord.out.bam processed/GAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAK1/Aligned.sortedByCoord.out.bam processed/GAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAK2/Aligned.sortedByCoord.out.bam processed/GAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAL1/Aligned.sortedByCoord.out.bam processed/GAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAL2/Aligned.sortedByCoord.out.bam processed/GAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAM1/Aligned.sortedByCoord.out.bam processed/GAM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAM2/Aligned.sortedByCoord.out.bam processed/GAM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAN1/Aligned.sortedByCoord.out.bam processed/GAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAN2/Aligned.sortedByCoord.out.bam processed/GAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAO1/Aligned.sortedByCoord.out.bam processed/GAO1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAO2/Aligned.sortedByCoord.out.bam processed/GAO2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAP1/Aligned.sortedByCoord.out.bam processed/GAP1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAP2/Aligned.sortedByCoord.out.bam processed/GAP2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAQ1/Aligned.sortedByCoord.out.bam processed/GAQ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAQ2/Aligned.sortedByCoord.out.bam processed/GAQ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAR1/Aligned.sortedByCoord.out.bam processed/GAR1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAR2/Aligned.sortedByCoord.out.bam processed/GAR2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAS1/Aligned.sortedByCoord.out.bam processed/GAS1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAS2-replicate/Aligned.sortedByCoord.out.bam processed/GAS2-replicate/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/GAS2/Aligned.sortedByCoord.out.bam processed/GAS2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAA1/Aligned.sortedByCoord.out.bam processed/HAA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAA2/Aligned.sortedByCoord.out.bam processed/HAA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAB1/Aligned.sortedByCoord.out.bam processed/HAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAB2/Aligned.sortedByCoord.out.bam processed/HAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAC1/Aligned.sortedByCoord.out.bam processed/HAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAC2/Aligned.sortedByCoord.out.bam processed/HAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAD1/Aligned.sortedByCoord.out.bam processed/HAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAD2/Aligned.sortedByCoord.out.bam processed/HAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAE1/Aligned.sortedByCoord.out.bam processed/HAE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAE2/Aligned.sortedByCoord.out.bam processed/HAE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAF1/Aligned.sortedByCoord.out.bam processed/HAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAF2/Aligned.sortedByCoord.out.bam processed/HAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAG1/Aligned.sortedByCoord.out.bam processed/HAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAG2/Aligned.sortedByCoord.out.bam processed/HAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAH1/Aligned.sortedByCoord.out.bam processed/HAH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAH2/Aligned.sortedByCoord.out.bam processed/HAH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAI1/Aligned.sortedByCoord.out.bam processed/HAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAI2/Aligned.sortedByCoord.out.bam processed/HAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAK1/Aligned.sortedByCoord.out.bam processed/HAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/HAK2/Aligned.sortedByCoord.out.bam processed/HAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAB1/Aligned.sortedByCoord.out.bam processed/JAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAB2/Aligned.sortedByCoord.out.bam processed/JAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAC1/Aligned.sortedByCoord.out.bam processed/JAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAC2/Aligned.sortedByCoord.out.bam processed/JAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAD1/Aligned.sortedByCoord.out.bam processed/JAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAD2/Aligned.sortedByCoord.out.bam processed/JAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAE1/Aligned.sortedByCoord.out.bam processed/JAE1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAE2/Aligned.sortedByCoord.out.bam processed/JAE2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAF1/Aligned.sortedByCoord.out.bam processed/JAF1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAF2/Aligned.sortedByCoord.out.bam processed/JAF2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAG1/Aligned.sortedByCoord.out.bam processed/JAG1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAG2/Aligned.sortedByCoord.out.bam processed/JAG2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAH1/Aligned.sortedByCoord.out.bam processed/JAH1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAH2/Aligned.sortedByCoord.out.bam processed/JAH2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAI1/Aligned.sortedByCoord.out.bam processed/JAI1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAI2/Aligned.sortedByCoord.out.bam processed/JAI2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAJ1/Aligned.sortedByCoord.out.bam processed/JAJ1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAJ2/Aligned.sortedByCoord.out.bam processed/JAJ2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAK1/Aligned.sortedByCoord.out.bam processed/JAK1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAK2/Aligned.sortedByCoord.out.bam processed/JAK2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAL1/Aligned.sortedByCoord.out.bam processed/JAL1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAL2/Aligned.sortedByCoord.out.bam processed/JAL2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAM1/Aligned.sortedByCoord.out.bam processed/JAM1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAM2/Aligned.sortedByCoord.out.bam processed/JAM2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAN1/Aligned.sortedByCoord.out.bam processed/JAN1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/JAN2/Aligned.sortedByCoord.out.bam processed/JAN2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAA1/Aligned.sortedByCoord.out.bam processed/KAA1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAA2/Aligned.sortedByCoord.out.bam processed/KAA2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAB1/Aligned.sortedByCoord.out.bam processed/KAB1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAB2/Aligned.sortedByCoord.out.bam processed/KAB2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAC1/Aligned.sortedByCoord.out.bam processed/KAC1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAC2/Aligned.sortedByCoord.out.bam processed/KAC2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAD1/Aligned.sortedByCoord.out.bam processed/KAD1/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAD2/Aligned.sortedByCoord.out.bam processed/KAD2/Aligned.sortedByCoord.out.markdup.bam
nice sambamba markdup -t 3 --overflow-list-size 1000000 --hash-table-size 1000000 processed/KAE1/Aligned.sortedByCoord.out.bam processed/KAE1/Aligned.sortedByCoord.out.markdup.bam
